### ISSUE TITLE
Amazing Mod!

### ISSUE THREAD

**Issue by Dyz89** [JacobG55/MultiCruiser#1]
First of all thank you for the mod, now i can potentially play bumper cars with my friends! so very much thank you for going the extra effort into giving cruisers collision and making this!.

If i may provide a suggestion? by all means you can disregard it, as what you have made is amazing already, however i looked for multi cruiser mods, due to there being a Mario Kart Moon.  But! is it possible to request a config to allow for shovels, shotguns, landmines or Lethal Things mod Rocket Launchers, to interact with the cruiser?
Currently the player cannot hit their cruiser, but if it could be enabled, one player can be on the back of the car with weapons and attempt to sabotage the other players Cruisers, llike a fun minigame!

Granted i would love it more if the driver / passenger could access their inventory or weaponry, but i think thats way to much programming and headaches to even consider. So only the ability to blast a cruiser with a shotgun.
This is just a wacky idea and once more i just wanna thank you for making this! im excited to get my friends to try this!

**Comment by JacobG55** [comment]
I think your suggestion may be out of scope for what I wanted this mod to be, but your idea sounds like amazing so I'll consider making a different mod to allow weapons to damage cruisers. I haven't heard of this mario kart moon before but your idea sounds really fun.

**Comment by JacobG55** [comment]
Hey so I've gone ahead and made the ability for the base game weapons to damage the cruiser similar to your suggestion in a new mod: https://thunderstore.io/c/lethal-company/p/JacobG5/HitIt/
This mod should work with the base game weapons, but I haven't tested it in a modded game. If there are any issues with it I'll look into it. For now, however, I'm marking this as closed, and further feedback on this idea can be put over at the new mod's location. Enjoy.
